name: Cross-Platform Builds

on:
  release:
    types: [created] # Triggers when a GitHub release is created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude: # Exclude unsupported combinations
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: linux
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Build
        run: |
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o lively-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/...

      - name: Archive and upload artifact
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ secrets.GITHUB_TOKEN }}
          asset_path: ./app-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: app-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream
